[settings]
experimental = true
legacy_version_file_disable_tools = ['terraform']

[tools]
terraform = "1.12.1"
trivy = "0.67.2"
terraform-docs = "0.20.0"
pre-commit = "4.5.0"
tflint = "0.60.0"
direnv = "2.37.1"
